In [1]:
import numpy as np

In [8]:
X_train = np.resize(np.arange(5, 20), new_shape=(15, 3))
X_train

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [30]:
y_train = np.random.randint(1, 5, size=(15,))

In [31]:
# 1 3 5 8
for i in range(y_train.shape[0]):
    print(f"{i}'th train: {y_train[i]}")

0'th train: 1
1'th train: 1
2'th train: 3
3'th train: 2
4'th train: 1
5'th train: 4
6'th train: 2
7'th train: 3
8'th train: 4
9'th train: 4
10'th train: 3
11'th train: 3
12'th train: 1
13'th train: 4
14'th train: 3


In [10]:
dists = np.random.randint(1, 25, size=(10, 15))
dists

array([[11,  6,  4,  7, 21, 14, 18,  3, 19,  2, 11,  8, 10,  5,  9],
       [22, 12, 14, 15, 22,  9, 23, 14, 11,  2,  5,  7, 15, 19,  9],
       [ 4,  2,  4, 11, 15, 20,  5,  2,  4, 11, 12, 18, 14,  7, 22],
       [ 8,  8,  8, 11,  9, 17,  7, 19,  6, 10, 20,  7, 17, 18,  4],
       [17,  3, 17,  6, 11, 18,  4, 10, 15,  9,  5, 17, 21, 13,  8],
       [12, 19, 10, 20, 17, 23, 13, 10, 18,  5, 13,  4, 11,  3, 13],
       [14, 17, 16,  4,  9, 23, 16, 15,  7, 21,  4, 22, 20, 17, 14],
       [ 3, 14,  2, 20, 18, 18, 20,  6,  4,  5, 14, 19,  4, 20, 16],
       [10,  7,  5, 24,  6,  2,  9, 20, 20, 12, 22,  8, 14, 12, 20],
       [ 5, 14, 19,  6, 13, 10, 15, 19, 21,  1, 14, 22, 10, 19, 21]])

In [46]:
k = 4
num_test = dists.shape[0]
y_test = np.zeros(shape=(num_test))
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
for i in range(num_test):
    vec_nums = np.argsort(dists[i])[:k]
    print(f"vec_nums_{i}: ***{vec_nums}***")
    closest_y = [y_train[vec_num] for vec_num in vec_nums]
    print(f"closest_y_{i}: {closest_y}")
    unq_labels, labels_counts = np.unique(closest_y, return_counts=True)
    print(unq_labels)
    print(labels_counts)
    y_test[i] = unq_labels[np.argmax(labels_counts)]
    print(y_test[i])

vec_nums_0: ***[ 9  7  2 13]***
closest_y_0: [4, 3, 3, 4]
[3 4]
[2 2]
3.0
vec_nums_1: ***[ 9 10 11  5]***
closest_y_1: [4, 3, 3, 4]
[3 4]
[2 2]
3.0
vec_nums_2: ***[1 7 0 2]***
closest_y_2: [1, 3, 1, 3]
[1 3]
[2 2]
1.0
vec_nums_3: ***[14  8  6 11]***
closest_y_3: [3, 4, 2, 3]
[2 3 4]
[1 2 1]
3.0
vec_nums_4: ***[ 1  6 10  3]***
closest_y_4: [1, 2, 3, 2]
[1 2 3]
[1 2 1]
2.0
vec_nums_5: ***[13 11  9  2]***
closest_y_5: [4, 3, 4, 3]
[3 4]
[2 2]
3.0
vec_nums_6: ***[ 3 10  8  4]***
closest_y_6: [2, 3, 4, 1]
[1 2 3 4]
[1 1 1 1]
1.0
vec_nums_7: ***[ 2  0  8 12]***
closest_y_7: [3, 1, 4, 1]
[1 3 4]
[2 1 1]
1.0
vec_nums_8: ***[5 2 4 1]***
closest_y_8: [4, 3, 1, 1]
[1 3 4]
[2 1 1]
1.0
vec_nums_9: ***[9 0 3 5]***
closest_y_9: [4, 1, 2, 4]
[1 2 4]
[1 1 2]
4.0


In [44]:
y_test

array([1., 1., 3., 3., 1., 1., 4., 2., 3., 3.])