In [1]:
import numpy as np

In [2]:
o = [1, 2, 3, 4, 5]
m = [[1, 2, 3, 4, 5,], [6, 7, 8, 9, 10,]]

In [3]:
a = np.array(o)

In [4]:
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
b = np.array(m)

In [6]:
print(b)
print(type(b))
print(b.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
(2, 5)


In [7]:
print(a.shape[0])

5


In [8]:
for i in range(a.shape[0]):
    print(a[i])

1
2
3
4
5


In [9]:
dists = np.zeros((10, 20))

In [10]:
dists

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [11]:
dists.shape

(10, 20)

In [12]:
rnd = np.arange(1, 81)
rnd

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [13]:
rnd = np.resize(a=rnd, new_shape=(10, 8))

In [14]:
rnd

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71, 72],
       [73, 74, 75, 76, 77, 78, 79, 80]])

In [15]:
rnd[1]

array([ 9, 10, 11, 12, 13, 14, 15, 16])

In [16]:
rnd[2]

array([17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
c = np.sqrt(np.sum(np.square(rnd[1] - rnd[2])))
c

22.627416997969522

In [18]:
x = np.random.randint(-10, 10, size=(5,))
x

array([ 5, -9,  1, -1, -3])

In [19]:
z = np.random.randint(-10, 10, size=(5,))
z

array([ 5,  8, -5,  2, -4])

In [20]:
t = x - z
t

array([  0, -17,   6,  -3,   1])

In [21]:
t_squared = np.square(t)
t_squared

array([  0, 289,  36,   9,   1])

In [22]:
t_squared_sum = np.sum(t_squared)
t_squared_sum

335

In [23]:
t_squared_sum_root = np.sqrt(t_squared_sum)
t_squared_sum_root

18.303005217723125

In [41]:
# q(1x6) w(15x6) e(1x10)
q = np.random.randint(-10, 11, size=(6,))
q

array([ 8,  1,  4, -2, -8, -1])

In [25]:
w = np.random.randint(-10, 11, size=(90,))
w = np.resize(w, new_shape=(15, 6))
w

array([[ -1,  10,  -5,  10,   2,  -6],
       [ -8,   6,   9,  -6,  -7,   3],
       [  0,   2,  -1,  -1,   8,   5],
       [  0,   9,  -3,   3,  -1,   0],
       [ -5,  -3,   2,  -1,   2,  -3],
       [ -3,   3,  -5,   5,   7,  -1],
       [ -8,   9,  -6,  -8,  -2,   8],
       [  5,   5,   7,  -5,  -5,   8],
       [  3,   8,   8,   7,  -8,  -9],
       [  9,  -8,  -7,  -7,   3,  -8],
       [  7,  -9, -10,  -9,   2,  -2],
       [ -5,  -8,  -7,   4,  10,  -9],
       [ -3,  -9,  -3,   5,  -6,  -3],
       [ 10,  -5,  -9,  -5,  -4,   6],
       [ -2,   1,  -8,   5,   2,  -5]])

In [31]:
w = np.transpose(w)
w

array([[ -1,  -8,   0,   0,  -5,  -3,  -8,   5,   3,   9,   7,  -5,  -3,
         10,  -2],
       [ 10,   6,   2,   9,  -3,   3,   9,   5,   8,  -8,  -9,  -8,  -9,
         -5,   1],
       [ -5,   9,  -1,  -3,   2,  -5,  -6,   7,   8,  -7, -10,  -7,  -3,
         -9,  -8],
       [ 10,  -6,  -1,   3,  -1,   5,  -8,  -5,   7,  -7,  -9,   4,   5,
         -5,   5],
       [  2,  -7,   8,  -1,   2,   7,  -2,  -5,  -8,   3,   2,  10,  -6,
         -4,   2],
       [ -6,   3,   5,   0,  -3,  -1,   8,   8,  -9,  -8,  -2,  -9,  -3,
          6,  -5]])

In [38]:
print(q)
print(q.shape)

[[ 4 -7 -2  7 -9 -5]]
(1, 6)


In [36]:
qwer = np.transpose(q)
print(qwer)
print(qwer.shape)

[ 6  1 -3 -5  5  9]
(6,)


In [39]:
e = w + q
e

ValueError: operands could not be broadcast together with shapes (6,15) (1,6) 

In [43]:
print(q)
q = q[:, np.newaxis]
print(q)
# abort transposing

[ 8  1  4 -2 -8 -1]
[[ 8]
 [ 1]
 [ 4]
 [-2]
 [-8]
 [-1]]


In [76]:
# q(1 x 6) w(15 x 6) e(1 x 15) dists(test x 15)
# q = np.arange(1, 7)
# q = np.resize(q, new_shape=(1, 6))
q = np.random.randint(-10, 11, size=(1, 6))
print('q')
print(q)
# w = np.arange(1, 7)
# w = np.resize(w, new_shape=(15, 6))
w = np.random.randint(-10, 11, size=(15, 6))
print('w')
print(w)
temp = w + q
print('temp')
print(temp)
temp = np.square(temp)
print('w')
print(w)
print('temp')
print(temp)
e = np.sqrt(np.sum(temp, axis=1))
print('e')
print(e)
print(e.shape)

q
[[-2 -9  1  7 -5  4]]
w
[[ -9  -2   3  -5   1  -7]
 [  7   3   3   9   0   1]
 [ -4  -1  -2 -10   7   1]
 [ -5   1   5  -9  -1  -6]
 [ -7  -7  -6  -6  -9   4]
 [ -1  -7  -3  -3  -1  -6]
 [ -3 -10  -6 -10 -10  -4]
 [ -9   7  -6  -4   4  -1]
 [  4   5   2   8   1  -1]
 [  1   8  -9  -6   3   5]
 [ -8   7   0   0   4  -9]
 [  0   7  10   2   6   1]
 [  8   4   1  -1  -6 -10]
 [  4 -10   7   6   1   9]
 [ -4   5   7  -5   1  10]]
temp
[[-11 -11   4   2  -4  -3]
 [  5  -6   4  16  -5   5]
 [ -6 -10  -1  -3   2   5]
 [ -7  -8   6  -2  -6  -2]
 [ -9 -16  -5   1 -14   8]
 [ -3 -16  -2   4  -6  -2]
 [ -5 -19  -5  -3 -15   0]
 [-11  -2  -5   3  -1   3]
 [  2  -4   3  15  -4   3]
 [ -1  -1  -8   1  -2   9]
 [-10  -2   1   7  -1  -5]
 [ -2  -2  11   9   1   5]
 [  6  -5   2   6 -11  -6]
 [  2 -19   8  13  -4  13]
 [ -6  -4   8   2  -4  14]]
w
[[ -9  -2   3  -5   1  -7]
 [  7   3   3   9   0   1]
 [ -4  -1  -2 -10   7   1]
 [ -5   1   5  -9  -1  -6]
 [ -7  -7  -6  -6  -9   4]
 [ -1  -7  -3  -3  -

In [80]:
print(np.sum(np.square(w + q), axis=1))

[287 383 175 193 623 325 645 169 279 152 180 236 258 783 332]


In [81]:
zs = np.zeros(shape=(30, 15))
zs

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [86]:
print(q)
print(w)

[[-2 -9  1  7 -5  4]]
[[ -9  -2   3  -5   1  -7]
 [  7   3   3   9   0   1]
 [ -4  -1  -2 -10   7   1]
 [ -5   1   5  -9  -1  -6]
 [ -7  -7  -6  -6  -9   4]
 [ -1  -7  -3  -3  -1  -6]
 [ -3 -10  -6 -10 -10  -4]
 [ -9   7  -6  -4   4  -1]
 [  4   5   2   8   1  -1]
 [  1   8  -9  -6   3   5]
 [ -8   7   0   0   4  -9]
 [  0   7  10   2   6   1]
 [  8   4   1  -1  -6 -10]
 [  4 -10   7   6   1   9]
 [ -4   5   7  -5   1  10]]


In [84]:
zs[0] = np.sqrt(np.sum(np.square(w - q), axis=1))
zs

array([[20.0748599 , 16.34013464, 22.7815715 , 22.29349681, 16.21727474,
        15.39480432, 20.71231518, 24.10394159, 17.17556404, 25.13961018,
        24.33105012, 22.27105745, 23.02172887, 11.61895004, 21.26029163],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        , 

In [116]:
# t(5x2) r(7x2) d(5x7)
t = np.random.randint(-5, 6, size=(5, 2))
r = np.random.randint(-5, 6, size=(7, 2))
d = np.zeros(shape=(5, 7))
print(t)
print()
print(r)
print()
print(np.transpose(r))

[[ 2  4]
 [ 2  1]
 [-2 -2]
 [ 1 -1]
 [-3  0]]

[[ 2  1]
 [-3 -2]
 [ 4 -3]
 [ 3 -1]
 [ 4 -2]
 [-4  0]
 [-4 -3]]

[[ 2 -3  4  3  4 -4 -4]
 [ 1 -2 -3 -1 -2  0 -3]]


In [117]:
# t(5x2) r(7x2) d(5x7)
d = np.sqrt((np.matmul(t, r.T) * -2) + np.sum(np.square(t), axis=1, keepdims=True) + np.sum(np.square(r), axis=1))
print(d)

[[3.         7.81024968 7.28010989 5.09901951 6.32455532 7.21110255
  9.21954446]
 [0.         5.83095189 4.47213595 2.23606798 3.60555128 6.08276253
  7.21110255]
 [5.         1.         6.08276253 5.09901951 6.         2.82842712
  2.23606798]
 [2.23606798 4.12310563 3.60555128 2.         3.16227766 5.09901951
  5.38516481]
 [5.09901951 2.         7.61577311 6.08276253 7.28010989 1.
  3.16227766]]


In [110]:
t_sqd = np.square(t)
t_sqd_sum = np.sum(t_sqd, axis=1, keepdims=True)

In [111]:
r_sqd = np.square(r)
r_sqd_sum = np.sum(r_sqd, axis=1)
d = d + r_sqd_sum

In [112]:
d = d + r_sqd_sum
print(d)

[[ 58  12  58 102  48  30 130]
 [ 92  22 -20 100  82 100 110]
 [ 42   4  42  70  88  30  90]
 [ 68  12 -12  72 108  80  80]
 [ 38   2  38  62  98  30  80]]


In [124]:
ex = np.round(d[0], decimals=1)
ex

array([3. , 7.8, 7.3, 5.1, 6.3, 7.2, 9.2])

In [140]:
p = np.argsort(d[0])[:k:-1]
k = 3
p

array([6, 1, 2], dtype=int64)

In [136]:
ids = p[:k]
ids

array([6, 1, 2], dtype=int64)

In [ ]:
self.y_train

In [132]:
for i in range(100):
    arr = np.array([i, 2*i])
    closest_y[i] = arr
print(closest_y)

NameError: name 'closest_y' is not defined

In [139]:
print(k)
temp = [j for j in range(k)]
print(temp)

3
[0, 1, 2]


In [145]:
y_train = np.array(['a', 'b', 'a', 'a', 'a', 'b', 'a', 'b', 'a', 'b'])

In [147]:
print(p)
temp1 = [y_train[trn_pnt] for trn_pnt in p]
temp1

[6 1 2]


['a', 'b', 'a']

In [169]:
last = np.array([10, 2, 7, 7, 7, 4, -1, 4, -1, 4, 3, 1, -1, 1])

In [170]:
unqs, counts = np.unique(last, return_counts=True)
print(unqs)
print(counts)

[-1  1  2  3  4  7 10]
[3 2 1 1 3 3 1]


In [171]:
label = unqs[np.argmax(counts)]
label

-1